name: ultimate_bottom_navbar
description: Ultimate Bottom Navigation Bar is a customizable bottom navigation bar for your Flutter applications.
version: 0.0.6
homepage: https://github.com/saginbajracharya/ultimate_bottom_navbar

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

screenshots:
  - description: 'Examples For All Types Of Ultimate Bottom NavBar.'
    path: doc/screenshots/All.png
  - description: 'Examples For Under Curve Bottom NavBar.'
    path: doc/screenshots/1.png
  - description: 'Examples For Under Curve with Gradient Background Bottom NavBar.'
    path: doc/screenshots/2.png
  - description: 'Examples For Upper Curve Bottom NavBar.'
    path: doc/screenshots/3.png
  - description: 'Examples For No Curve/No ForeGround Bottom NavBar.'
    path: doc/screenshots/4.png
  - description: 'Examples For No Curve/No ForeGround With Margin Bottom NavBar.'
    path: doc/screenshots/5.png
  - description: 'Examples For Under Curve With Custom Selected Decor Bottom NavBar.'
    path: doc/screenshots/6.png
  - description: 'Examples For No Curve, Custom Selected Decor And Gradient Background and Stroke Border Bottom NavBar.'
    path: doc/screenshots/7.png
  - description: 'Examples of the Under Curve With Margin Bottom NavBar.'
    path: doc/screenshots/8.png

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
